name: Erasmus Botunu Calistir

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# Botun depoya dosya kaydedebilmesi için yazma izni veriyoruz
permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Gerekli Paketleri Yükle
        run: pip install requests beautifulsoup4

      - name: Botu Çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py

      - name: Hafızayı GitHub'a Kaydet
        run: |
          git config --global user.name "Erasmus Bot"
          git config --global user.email "bot@erasmusradar.com"
          git add gecmis_ilanlar.txt || true
          git commit -m "Hafiza guncellendi" || echo "Degisiklik yok"
          git push || true
